version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  
  test-app:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v
  
  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t karsajobs:latest .
      - run:
          name: Tag Image
          command: docker image tag karsajobs:latest ghcr.io/cobrasan86/karsajobs:latest
      - run:
          name: Login Github Packages
          command: echo $TOKENKU | docker login ghcr.io -u cobrasan86 --password-stdin
      - run:
          name: Push Image ke Github Packages
          command: docker image push ghcr.io/cobrasan86/karsajobs:latest
          
workflows:
  version: 2
  kiwkiw:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs